import type { Bookmark, Category, Collection, Tag } from './types';

const now = Date.now();
const daysAgo = (n: number) => new Date(now - n * 86400000).toISOString();
const hoursAgo = (n: number) => new Date(now - n * 3600000).toISOString();

export const tags: Tag[] = [
  { id: 't-css', label: 'CSS', color: 'blue' },
  { id: 't-react', label: 'React', color: 'blue' },
  { id: 't-design', label: '设计', color: 'violet' },
  { id: 't-inspiration', label: '灵感', color: 'amber' },
  { id: 't-tool', label: '工具', color: 'green' },
  { id: 't-doc', label: '文档', color: 'gray' },
  { id: 't-tutorial', label: '教程', color: 'green' },
  { id: 't-color', label: '配色', color: 'coral' },
  { id: 't-font', label: '字体', color: 'coral' },
  { id: 't-a11y', label: '无障碍', color: 'amber' },
  { id: 't-ai', label: 'AI', color: 'violet' },
  { id: 't-ux', label: 'UX', color: 'violet' },
  { id: 't-perf', label: '性能', color: 'amber' },
  { id: 't-api', label: 'API', color: 'blue' },
  { id: 't-competition', label: '竞品', color: 'coral' },
];

export const categories: Category[] = [
  { id: 'c-tech', name: '技术', icon: 'Code2', parentId: null, color: 'blue' },
  { id: 'c-fe', name: '前端', icon: 'MonitorSmartphone', parentId: 'c-tech', color: 'blue' },
  { id: 'c-css', name: 'CSS', icon: 'Palette', parentId: 'c-fe', color: 'coral' },
  { id: 'c-react', name: 'React', icon: 'Atom', parentId: 'c-fe', color: 'blue' },
  { id: 'c-perf', name: '性能优化', icon: 'Gauge', parentId: 'c-fe', color: 'amber' },
  { id: 'c-be', name: '后端', icon: 'Server', parentId: 'c-tech', color: 'green' },
  { id: 'c-ai', name: 'AI / ML', icon: 'Sparkles', parentId: 'c-tech', color: 'violet' },

  { id: 'c-design', name: '设计', icon: 'PenTool', parentId: null, color: 'violet' },
  { id: 'c-ui', name: 'UI 组件', icon: 'Shapes', parentId: 'c-design', color: 'violet' },
  { id: 'c-color', name: '配色', icon: 'Droplet', parentId: 'c-design', color: 'coral' },
  { id: 'c-type', name: '字体排版', icon: 'Type', parentId: 'c-design', color: 'coral' },

  { id: 'c-product', name: '产品', icon: 'Lightbulb', parentId: null, color: 'amber' },
  { id: 'c-compete', name: '竞品分析', icon: 'ScanSearch', parentId: 'c-product', color: 'coral' },
  { id: 'c-read', name: '阅读收藏', icon: 'BookOpen', parentId: null, color: 'gray' },
];

export const collections: Collection[] = [
  {
    id: 'col-inspiration',
    name: '设计灵感',
    emoji: '🎨',
    color: 'violet',
    description: '配色、字体、优秀案例与竞品视觉的聚合空间',
    bookmarkIds: ['b-coolors', 'b-fontpair', 'b-awwwards', 'b-dribbble', 'b-mobbin'],
  },
  {
    id: 'col-build',
    name: '搭建个人站',
    emoji: '🛠️',
    color: 'blue',
    description: '从框架到部署，落地这个项目所需的一切',
    bookmarkIds: ['b-react', 'b-tailwind', 'b-vite', 'b-vercel'],
  },
  {
    id: 'col-aiexp',
    name: 'AI 实验场',
    emoji: '🧪',
    color: 'violet',
    description: '值得动手试试的模型、SDK 与论文',
    bookmarkIds: ['b-openai', 'b-transformers', 'b-langchain', 'b-gpu'],
  },
  {
    id: 'col-ship',
    name: '本周要交付',
    emoji: '🚀',
    color: 'amber',
    description: '短期任务相关的参考与工具',
    bookmarkIds: ['b-react', 'b-mdn', 'b-webdev', 'b-canliuse'],
  },
  {
    id: 'col-read',
    name: '周末长读',
    emoji: '📚',
    color: 'green',
    description: '留到有大块时间细读的长文与论文',
    bookmarkIds: ['b-smashing', 'b-css-tricks', 'b-transformers'],
  },
];

export const bookmarks: Bookmark[] = [
  {
    id: 'b-coolors',
    title: 'Coolors — 超快配色方案生成器',
    url: 'https://coolors.co',
    domain: 'coolors.co',
    favicon: '🎨',
    faviconColor: 'coral',
    description: '按空格生成新配色，锁定喜欢的色相，导出多种格式。',
    notes: '## 用法\n- 按 **空格** 随机生成\n- 锁定色相后微调明度\n- 导出 PNG / HEX / CSS\n适合做品牌主色快速试错。',
    tags: ['t-color', 't-tool', 't-design'],
    categoryId: 'c-color',
    collectionIds: ['col-inspiration'],
    createdAt: daysAgo(42),
    lastVisitedAt: hoursAgo(6),
    visitCount: 38,
    starred: true,
    pinned: true,
    thumbnail: 'coral',
    health: 'ok',
    aiSummary: '快速生成、锁定与导出配色方案的在线工具，支持色盲模拟与对比度检查。',
    aiSuggestedTags: ['t-color', 't-tool'],
    spark: [2, 5, 3, 8, 6, 12, 9, 14, 11, 18, 15, 22],
  },
  {
    id: 'b-fontpair',
    title: 'Font Pair — 帮你搭配好看的字体组合',
    url: 'https://www.fontpair.co',
    domain: 'fontpair.co',
    favicon: '🔤',
    faviconColor: 'coral',
    description: '展示 Google Fonts 字体配对案例，一键复制 CSS。',
    notes: '标题用 **Playfair Display** + 正文 **Inter** 的组合很稳。',
    tags: ['t-font', 't-design'],
    categoryId: 'c-type',
    collectionIds: ['col-inspiration'],
    createdAt: daysAgo(30),
    lastVisitedAt: daysAgo(2),
    visitCount: 14,
    starred: false,
    pinned: false,
    thumbnail: 'violet',
    health: 'ok',
    aiSummary: '精选 Google Fonts 配对方案库，含预览与可直接复用的 font-family 声明。',
    spark: [1, 0, 2, 1, 3, 2, 4, 3, 5, 4, 6, 5],
  },
  {
    id: 'b-awwwards',
    title: 'Awwwards — 优秀网页设计颁奖',
    url: 'https://www.awwwards.com',
    domain: 'awwwards.com',
    favicon: '🏆',
    faviconColor: 'amber',
    description: '每日评选全球最佳网页设计，含交互与开发评分。',
    notes: '看 motion 与 site of the day 找灵感。',
    tags: ['t-inspiration', 't-design', 't-ux'],
    categoryId: 'c-ui',
    collectionIds: ['col-inspiration'],
    createdAt: daysAgo(60),
    lastVisitedAt: daysAgo(1),
    visitCount: 52,
    starred: true,
    pinned: false,
    thumbnail: 'amber',
    health: 'ok',
    aiSummary: '国际网页设计奖项站点，按日/月展示获奖作品并附带评审维度。',
    spark: [6, 8, 5, 10, 9, 12, 11, 15, 14, 18, 20, 24],
  },
  {
    id: 'b-dribbble',
    title: 'Dribbble — 设计师作品社区',
    url: 'https://dribbble.com',
    domain: 'dribbble.com',
    favicon: '🏀',
    faviconColor: 'coral',
    description: '设计师展示作品的社区，按颜色/标签筛选 shots。',
    notes: '',
    tags: ['t-inspiration', 't-design'],
    categoryId: 'c-ui',
    collectionIds: ['col-inspiration'],
    createdAt: daysAgo(80),
    lastVisitedAt: daysAgo(3),
    visitCount: 27,
    starred: false,
    pinned: false,
    thumbnail: 'coral',
    health: 'ok',
    aiSummary: '全球设计师作品展示社区，支持按色彩、标签、工具筛选可视化作品。',
    spark: [4, 3, 5, 4, 6, 5, 7, 6, 8, 7, 9, 8],
  },
  {
    id: 'b-mobbin',
    title: 'Mobbin — 移动端 UI 设计模式库',
    url: 'https://mobbin.com',
    domain: 'mobbin.com',
    favicon: '📱',
    faviconColor: 'blue',
    description: '收录大量真实 App 的界面截图，按流程/组件检索。',
    notes: '做登录流、空状态时翻一翻。',
    tags: ['t-inspiration', 't-ux', 't-design'],
    categoryId: 'c-ui',
    collectionIds: ['col-inspiration'],
    createdAt: daysAgo(20),
    lastVisitedAt: hoursAgo(30),
    visitCount: 19,
    starred: true,
    pinned: false,
    thumbnail: 'blue',
    health: 'changed',
    aiSummary: '真实移动应用界面截图库，按用户流程与 UI 组件分类索引。',
    spark: [2, 3, 2, 4, 3, 5, 4, 6, 5, 7, 6, 9],
  },
  {
    id: 'b-react',
    title: 'React 官方文档',
    url: 'https://react.dev',
    domain: 'react.dev',
    favicon: '⚛️',
    faviconColor: 'blue',
    description: 'React 19 官方文档，含交互式教程与 API 参考。',
    notes: '## 常查\n- [Hooks](https://react.dev/reference/react)\n- Server Components\n- use()',
    tags: ['t-react', 't-doc'],
    categoryId: 'c-react',
    collectionIds: ['col-build', 'col-ship'],
    createdAt: daysAgo(120),
    lastVisitedAt: hoursAgo(2),
    visitCount: 96,
    starred: true,
    pinned: true,
    thumbnail: 'blue',
    health: 'ok',
    aiSummary: 'React 官方文档站点，涵盖 Hooks、Server Components 与交互式教程。',
    spark: [10, 12, 14, 18, 20, 25, 28, 30, 35, 40, 44, 50],
  },
  {
    id: 'b-tailwind',
    title: 'Tailwind CSS — 实用优先的 CSS 框架',
    url: 'https://tailwindcss.com',
    domain: 'tailwindcss.com',
    favicon: '🌊',
    faviconColor: 'blue',
    description: '原子化 CSS 框架文档与配置参考。',
    notes: 'JIT 模式下自定义颜色用 `theme.extend`。',
    tags: ['t-css', 't-doc', 't-tool'],
    categoryId: 'c-css',
    collectionIds: ['col-build'],
    createdAt: daysAgo(110),
    lastVisitedAt: hoursAgo(4),
    visitCount: 73,
    starred: false,
    pinned: false,
    thumbnail: 'blue',
    health: 'ok',
    aiSummary: '实用优先的 CSS 框架官方文档，含配置、主题与组件示例。',
    spark: [8, 10, 12, 14, 16, 18, 20, 22, 24, 28, 30, 34],
  },
  {
    id: 'b-vite',
    title: 'Vite — 下一代前端构建工具',
    url: 'https://vitejs.dev',
    domain: 'vitejs.dev',
    favicon: '⚡',
    faviconColor: 'amber',
    description: '基于原生 ESM 的极速开发服务器与构建工具。',
    notes: 'HMR 飞快，生产构建用 Rollup。',
    tags: ['t-tool', 't-perf', 't-doc'],
    categoryId: 'c-fe',
    collectionIds: ['col-build'],
    createdAt: daysAgo(95),
    lastVisitedAt: daysAgo(5),
    visitCount: 41,
    starred: false,
    pinned: false,
    thumbnail: 'amber',
    health: 'ok',
    aiSummary: '基于原生 ESM 的前端构建工具文档，含插件 API 与部署指南。',
    spark: [5, 6, 8, 7, 10, 9, 12, 11, 14, 13, 16, 15],
  },
  {
    id: 'b-vercel',
    title: 'Vercel — 前端部署与托管平台',
    url: 'https://vercel.com',
    domain: 'vercel.com',
    favicon: '▲',
    faviconColor: 'gray',
    description: '连接 Git 仓库即可自动部署，支持边缘函数与预览部署。',
    notes: 'Preview Deployments 方便给设计评审。',
    tags: ['t-tool', 't-doc'],
    categoryId: 'c-fe',
    collectionIds: ['col-build'],
    createdAt: daysAgo(88),
    lastVisitedAt: daysAgo(1),
    visitCount: 33,
    starred: false,
    pinned: false,
    thumbnail: 'gray',
    health: 'ok',
    aiSummary: '面向前端的部署平台，支持预览部署、边缘函数与自动 HTTPS。',
    spark: [3, 4, 5, 6, 6, 7, 8, 9, 9, 10, 11, 12],
  },
  {
    id: 'b-mdn',
    title: 'MDN Web Docs',
    url: 'https://developer.mozilla.org',
    domain: 'developer.mozilla.org',
    favicon: '📖',
    faviconColor: 'blue',
    description: 'Mozilla 维护的 Web 平台权威参考文档。',
    notes: '查 CSS 属性、JS API 的兼容性与语法首选。',
    tags: ['t-doc', 't-css'],
    categoryId: 'c-css',
    collectionIds: ['col-ship'],
    createdAt: daysAgo(150),
    lastVisitedAt: hoursAgo(10),
    visitCount: 120,
    starred: true,
    pinned: false,
    thumbnail: 'blue',
    health: 'ok',
    aiSummary: 'Mozilla 维护的 Web 平台文档，涵盖 HTML、CSS、JS 与浏览器兼容性。',
    spark: [15, 18, 20, 22, 25, 28, 30, 33, 36, 40, 44, 48],
  },
  {
    id: 'b-webdev',
    title: 'web.dev — Google Web 开发最佳实践',
    url: 'https://web.dev',
    domain: 'web.dev',
    favicon: '🅖',
    faviconColor: 'green',
    description: '性能、无障碍、SEO 等质量的系统化指南。',
    notes: 'Core Web Vitals 系列文章值得精读。',
    tags: ['t-perf', 't-a11y', 't-doc', 't-tutorial'],
    categoryId: 'c-perf',
    collectionIds: ['col-ship'],
    createdAt: daysAgo(70),
    lastVisitedAt: daysAgo(2),
    visitCount: 48,
    starred: false,
    pinned: false,
    thumbnail: 'green',
    health: 'ok',
    aiSummary: 'Google 出品的 Web 质量指南，聚焦性能、无障碍与 SEO。',
    spark: [4, 6, 5, 8, 7, 10, 9, 12, 11, 14, 13, 16],
  },
  {
    id: 'b-canliuse',
    title: 'Can I Use — 浏览器特性兼容性表',
    url: 'https://caniuse.com',
    domain: 'caniuse.com',
    favicon: '✅',
    faviconColor: 'green',
    description: '查询 CSS / JS / API 在各浏览器的支持情况。',
    notes: '',
    tags: ['t-doc', 't-tool', 't-css'],
    categoryId: 'c-css',
    collectionIds: ['col-ship'],
    createdAt: daysAgo(130),
    lastVisitedAt: daysAgo(4),
    visitCount: 65,
    starred: false,
    pinned: false,
    thumbnail: 'green',
    health: 'ok',
    aiSummary: '浏览器特性兼容性数据库，提供按版本的支持矩阵与全局占比。',
    spark: [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
  },
  {
    id: 'b-openai',
    title: 'OpenAI Platform',
    url: 'https://platform.openai.com',
    domain: 'platform.openai.com',
    favicon: '🤖',
    faviconColor: 'green',
    description: 'OpenAI API 文档、Playground 与模型定价。',
    notes: 'function calling 与 vision 的接入示例在此。',
    tags: ['t-ai', 't-api', 't-doc'],
    categoryId: 'c-ai',
    collectionIds: ['col-aiexp'],
    createdAt: daysAgo(45),
    lastVisitedAt: hoursAgo(8),
    visitCount: 29,
    starred: true,
    pinned: false,
    thumbnail: 'green',
    health: 'changed',
    aiSummary: 'OpenAI 开发者平台，含 API 文档、模型定价与交互式 Playground。',
    spark: [3, 5, 4, 7, 6, 9, 8, 11, 10, 13, 12, 15],
  },
  {
    id: 'b-transformers',
    title: 'Hugging Face Transformers 文档',
    url: 'https://huggingface.co/docs/transformers',
    domain: 'huggingface.co',
    favicon: '🤗',
    faviconColor: 'amber',
    description: 'Transformers 库官方文档，含模型卡与微调教程。',
    notes: '从入门到微调 BERT 的教程很完整。',
    tags: ['t-ai', 't-doc', 't-tutorial'],
    categoryId: 'c-ai',
    collectionIds: ['col-aiexp', 'col-read'],
    createdAt: daysAgo(55),
    lastVisitedAt: daysAgo(6),
    visitCount: 22,
    starred: false,
    pinned: false,
    thumbnail: 'amber',
    health: 'ok',
    aiSummary: 'Transformers 库文档，涵盖预训练模型、微调与部署流程。',
    spark: [2, 3, 3, 4, 5, 5, 6, 7, 7, 8, 9, 10],
  },
  {
    id: 'b-langchain',
    title: 'LangChain — LLM 应用框架',
    url: 'https://python.langchain.com',
    domain: 'python.langchain.com',
    favicon: '🔗',
    faviconColor: 'blue',
    description: '构建 LLM 链式应用与 Agent 的框架文档。',
    notes: 'LangGraph 做多步 Agent 的状态机挺清晰。',
    tags: ['t-ai', 't-doc', 't-tool'],
    categoryId: 'c-ai',
    collectionIds: ['col-aiexp'],
    createdAt: daysAgo(35),
    lastVisitedAt: daysAgo(3),
    visitCount: 18,
    starred: false,
    pinned: false,
    thumbnail: 'blue',
    health: 'ok',
    aiSummary: '用于编排 LLM、检索与工具调用的应用框架文档。',
    spark: [1, 2, 2, 3, 3, 4, 5, 5, 6, 7, 7, 8],
  },
  {
    id: 'b-gpu',
    title: 'RunPod — GPU 按需租赁',
    url: 'https://www.runpod.io',
    domain: 'runpod.io',
    favicon: '🖥️',
    faviconColor: 'violet',
    description: '按小时租赁 GPU 实例，用于模型训练与推理。',
    notes: 'A100 按小时计费，跑微调够用。',
    tags: ['t-ai', 't-tool'],
    categoryId: 'c-ai',
    collectionIds: ['col-aiexp'],
    createdAt: daysAgo(25),
    lastVisitedAt: daysAgo(7),
    visitCount: 9,
    starred: false,
    pinned: false,
    thumbnail: 'violet',
    health: 'ok',
    aiSummary: 'GPU 云算力租赁平台，支持按需启动与容器化部署。',
    spark: [1, 1, 2, 2, 2, 3, 3, 4, 4, 5, 5, 6],
  },
  {
    id: 'b-smashing',
    title: 'Smashing Magazine — 前端深度文章',
    url: 'https://www.smashingmagazine.com',
    domain: 'smashingmagazine.com',
    favicon: '✍️',
    faviconColor: 'coral',
    description: '前端与设计深度文章及电子书。',
    notes: 'CSS 架构系列值得收藏细读。',
    tags: ['t-tutorial', 't-css', 't-design'],
    categoryId: 'c-read',
    collectionIds: ['col-read'],
    createdAt: daysAgo(90),
    lastVisitedAt: daysAgo(9),
    visitCount: 16,
    starred: false,
    pinned: false,
    thumbnail: 'coral',
    health: 'ok',
    aiSummary: '面向前端与设计的内容站点，发布深度教程与行业文章。',
    spark: [2, 2, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6],
  },
  {
    id: 'b-css-tricks',
    title: 'CSS-Tricks — CSS 技巧与指南',
    url: 'https://css-tricks.com',
    domain: 'css-tricks.com',
    favicon: '🧰',
    faviconColor: 'blue',
    description: 'CSS 技巧、Flex/Grid 完整指南等经典资源。',
    notes: 'A Complete Guide to Grid 是翻得最多的页面。',
    tags: ['t-css', 't-tutorial', 't-doc'],
    categoryId: 'c-css',
    collectionIds: ['col-read'],
    createdAt: daysAgo(140),
    lastVisitedAt: daysAgo(11),
    visitCount: 44,
    starred: false,
    pinned: false,
    thumbnail: 'blue',
    health: 'ok',
    aiSummary: 'CSS 技巧与指南站点，包含 Flexbox、Grid 经典完整指南。',
    spark: [5, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11],
  },
  {
    id: 'b-figma',
    title: 'Figma — 协作式界面设计工具',
    url: 'https://www.figma.com',
    domain: 'figma.com',
    favicon: '🎯',
    faviconColor: 'violet',
    description: '实时协作的界面设计与原型工具。',
    notes: 'Dev Mode 直接拷贝 CSS 变量很方便。',
    tags: ['t-design', 't-tool', 't-ux'],
    categoryId: 'c-ui',
    collectionIds: ['col-inspiration'],
    createdAt: daysAgo(160),
    lastVisitedAt: hoursAgo(1),
    visitCount: 88,
    starred: true,
    pinned: true,
    thumbnail: 'violet',
    health: 'ok',
    aiSummary: '协作式界面设计工具，支持原型、Dev Mode 与团队组件库。',
    spark: [10, 12, 15, 18, 20, 24, 28, 32, 36, 42, 48, 56],
  },
];

export function getTag(id: string) {
  return tags.find((t) => t.id === id);
}
export function getCategory(id: string) {
  return categories.find((c) => c.id === id);
}
export function getCollection(id: string) {
  return collections.find((c) => c.id === id);
}
export function getBookmark(id: string) {
  return bookmarks.find((b) => b.id === id);
}
