import type { Bookmark, Category, Collection, Tag } from './types';

const now = Date.now();
const daysAgo = (n: number) => new Date(now - n * 86400000).toISOString();
const hoursAgo = (n: number) => new Date(now - n * 3600000).toISOString();

export const tags: Tag[] = [
  { id: 't-css', label: 'CSS', color: 'blue' },
  { id: 't-design', label: 'Design', color: 'violet' },
  { id: 't-tool', label: 'Tools', color: 'green' },
  { id: 't-doc', label: 'Doc', color: 'gray' },
];

export const categories: Category[] = [
  { id: 'c-tech', name: 'Engineering', icon: 'Code2', parentId: null, color: 'blue' },
  { id: 'c-fe', name: 'Frontend', icon: 'MonitorSmartphone', parentId: 'c-tech', color: 'blue' },
  { id: 'c-css', name: 'CSS & Styling', icon: 'Palette', parentId: 'c-fe', color: 'coral' },
  { id: 'c-be', name: 'Backend', icon: 'Server', parentId: 'c-tech', color: 'green' },
  { id: 'c-ai', name: 'AI & ML', icon: 'Sparkles', parentId: 'c-tech', color: 'violet' },

  { id: 'c-design', name: 'Design', icon: 'PenTool', parentId: null, color: 'violet' },
  { id: 'c-ui', name: 'UI Components', icon: 'Shapes', parentId: 'c-design', color: 'violet' },
];

export const collections: Collection[] = [
  {
    id: 'col-inspiration',
    name: 'Design',
    emoji: '🎨',
    color: 'violet',
    description: 'Curated showcases, design systems, and visual inspiration',
    bookmarkIds: ['b-coolors', 'b-awwwards', 'b-dribbble', 'b-figma'],
  },
  {
    id: 'col-build',
    name: 'Web',
    emoji: '🛠️',
    color: 'blue',
    description: 'Frameworks, documentation, and tools for modern web applications',
    bookmarkIds: ['b-tailwind', 'b-vite', 'b-vercel', 'b-mdn', 'b-openai'],
  },
];

export const bookmarks: Bookmark[] = [
  {
    id: 'b-coolors',
    title: 'Coolors — Super Fast Color Schemes Generator',
    url: 'https://coolors.co',
    domain: 'coolors.co',
    favicon: '🎨',
    faviconColor: 'coral',
    description: 'Generate or browse beautiful color combinations for your designs.',
    notes: '## Quick Tips\n- Press **Spacebar** to generate palettes\n- Lock colors and export as PNG, HEX, or CSS.',
    tags: ['t-design', 't-tool'],
    categoryId: 'c-ui',
    collectionIds: ['col-inspiration'],
    createdAt: daysAgo(42),
    lastVisitedAt: hoursAgo(6),
    visitCount: 38,
    starred: true,
    pinned: true,
    thumbnail: 'coral',
    health: 'ok',
    aiSummary: 'Online color palette generator with blind simulation and contrast checking.',
    aiSuggestedTags: ['t-design', 't-tool'],
    spark: [2, 5, 3, 8, 6, 12, 9, 14, 11, 18, 15, 22],
  },
  {
    id: 'b-awwwards',
    title: 'Awwwards — Website Awards & Design Inspiration',
    url: 'https://www.awwwards.com',
    domain: 'awwwards.com',
    favicon: '🏆',
    faviconColor: 'amber',
    description: 'Recognizing and promoting the talent of the best web designers worldwide.',
    notes: 'Great for motion design and layout inspiration.',
    tags: ['t-design'],
    categoryId: 'c-ui',
    collectionIds: ['col-inspiration'],
    createdAt: daysAgo(60),
    lastVisitedAt: daysAgo(1),
    visitCount: 52,
    starred: true,
    pinned: false,
    thumbnail: 'amber',
    health: 'ok',
    aiSummary: 'Web design award platform showcasing Site of the Day entries.',
    spark: [6, 8, 5, 10, 9, 12, 11, 15, 14, 18, 20, 24],
  },
  {
    id: 'b-dribbble',
    title: 'Dribbble — Discover the World’s Top Designers',
    url: 'https://dribbble.com',
    domain: 'dribbble.com',
    favicon: '🏀',
    faviconColor: 'coral',
    description: 'Design community showcasing creative portfolios and UI shots.',
    notes: '',
    tags: ['t-design'],
    categoryId: 'c-ui',
    collectionIds: ['col-inspiration'],
    createdAt: daysAgo(80),
    lastVisitedAt: daysAgo(3),
    visitCount: 27,
    starred: false,
    pinned: false,
    thumbnail: 'coral',
    health: 'ok',
    aiSummary: 'Global portfolio community for designers to showcase visual UI shots.',
    spark: [4, 3, 5, 4, 6, 5, 7, 6, 8, 7, 9, 8],
  },
  {
    id: 'b-tailwind',
    title: 'Tailwind CSS — Utility-First CSS Framework',
    url: 'https://tailwindcss.com',
    domain: 'tailwindcss.com',
    favicon: '🌊',
    faviconColor: 'blue',
    description: 'A utility-first CSS framework packed with classes for rapid UI development.',
    notes: 'Use theme.extend in tailwind.config.js for custom design tokens.',
    tags: ['t-css', 't-doc', 't-tool'],
    categoryId: 'c-css',
    collectionIds: ['col-build'],
    createdAt: daysAgo(110),
    lastVisitedAt: hoursAgo(4),
    visitCount: 73,
    starred: false,
    pinned: false,
    thumbnail: 'blue',
    health: 'ok',
    aiSummary: 'Utility-first CSS framework official documentation.',
    spark: [8, 10, 12, 14, 16, 18, 20, 22, 24, 28, 30, 34],
  },
  {
    id: 'b-vite',
    title: 'Vite — Next Generation Frontend Tooling',
    url: 'https://vitejs.dev',
    domain: 'vitejs.dev',
    favicon: '⚡',
    faviconColor: 'amber',
    description: 'Fast development server and bundling tool powered by native ESM.',
    notes: 'Lightning-fast HMR and optimized production builds.',
    tags: ['t-tool', 't-doc'],
    categoryId: 'c-fe',
    collectionIds: ['col-build'],
    createdAt: daysAgo(95),
    lastVisitedAt: daysAgo(5),
    visitCount: 41,
    starred: false,
    pinned: false,
    thumbnail: 'amber',
    health: 'ok',
    aiSummary: 'Frontend build tool documentation with plugin API and deployment guides.',
    spark: [5, 6, 8, 7, 10, 9, 12, 11, 14, 13, 16, 15],
  },
  {
    id: 'b-vercel',
    title: 'Vercel — Build and Deploy Web Applications',
    url: 'https://vercel.com',
    domain: 'vercel.com',
    favicon: '▲',
    faviconColor: 'gray',
    description: 'Developer platform for frontend frameworks and serverless functions.',
    notes: 'Preview deployments make design reviews effortless.',
    tags: ['t-tool', 't-doc'],
    categoryId: 'c-fe',
    collectionIds: ['col-build'],
    createdAt: daysAgo(88),
    lastVisitedAt: daysAgo(1),
    visitCount: 33,
    starred: false,
    pinned: false,
    thumbnail: 'gray',
    health: 'ok',
    aiSummary: 'Deployment platform for frontend apps supporting automatic HTTPS and edge functions.',
    spark: [3, 4, 5, 6, 6, 7, 8, 9, 9, 10, 11, 12],
  },
  {
    id: 'b-mdn',
    title: 'MDN Web Docs',
    url: 'https://developer.mozilla.org',
    domain: 'developer.mozilla.org',
    favicon: '📖',
    faviconColor: 'blue',
    description: 'Documenting web technologies including HTML, CSS, and JavaScript APIs.',
    notes: 'Essential reference for CSS specifications and browser compatibility.',
    tags: ['t-doc', 't-css'],
    categoryId: 'c-css',
    collectionIds: ['col-build'],
    createdAt: daysAgo(150),
    lastVisitedAt: hoursAgo(10),
    visitCount: 120,
    starred: true,
    pinned: false,
    thumbnail: 'blue',
    health: 'ok',
    aiSummary: 'Comprehensive web platform reference documentation by Mozilla.',
    spark: [15, 18, 20, 22, 25, 28, 30, 33, 36, 40, 44, 48],
  },
  {
    id: 'b-figma',
    title: 'Figma — Collaborative Interface Design Tool',
    url: 'https://www.figma.com',
    domain: 'figma.com',
    favicon: '🎯',
    faviconColor: 'violet',
    description: 'The collaborative interface design tool for vector graphics and prototyping.',
    notes: 'Dev Mode allows easy inspection of CSS variables.',
    tags: ['t-design', 't-tool'],
    categoryId: 'c-ui',
    collectionIds: ['col-inspiration'],
    createdAt: daysAgo(160),
    lastVisitedAt: hoursAgo(1),
    visitCount: 88,
    starred: true,
    pinned: true,
    thumbnail: 'violet',
    health: 'ok',
    aiSummary: 'Cloud-based UI design application for design teams.',
    spark: [10, 12, 15, 18, 20, 24, 28, 32, 36, 42, 48, 56],
  },
  {
    id: 'b-openai',
    title: 'OpenAI Platform & API Docs',
    url: 'https://platform.openai.com',
    domain: 'platform.openai.com',
    favicon: '🤖',
    faviconColor: 'green',
    description: 'API documentation, interactive playground, and AI model developer resources.',
    notes: 'Check function calling and structured outputs guides.',
    tags: ['t-doc', 't-tool'],
    categoryId: 'c-ai',
    collectionIds: ['col-build'],
    createdAt: daysAgo(45),
    lastVisitedAt: hoursAgo(8),
    visitCount: 29,
    starred: true,
    pinned: false,
    thumbnail: 'green',
    health: 'changed',
    aiSummary: 'Developer portal for OpenAI API services and model documentation.',
    spark: [3, 5, 4, 7, 6, 9, 8, 11, 10, 13, 12, 15],
  },
];

export function getTag(id: string) {
  return tags.find((t) => t.id === id);
}
export function getCategory(id: string) {
  return categories.find((c) => c.id === id);
}
export function getCollection(id: string) {
  return collections.find((c) => c.id === id);
}
export function getBookmark(id: string) {
  return bookmarks.find((b) => b.id === id);
}
