package config

const (
	ErrorCodeInvalidArgument  = "INVALID_ARGUMENT"
	ErrorCodeDocumentInvalid  = "DOCUMENT_INVALID"
	ErrorCodeSettingsInvalid  = "SETTINGS_INVALID"
	ErrorCodeImportInvalid        = "IMPORT_INVALID"
	ErrorCodeExportInvalid        = "EXPORT_INVALID"
	ErrorCodeURLInvalid          = "URL_INVALID"
	ErrorCodeMetadataFetchFailed = "METADATA_FETCH_FAILED"
	ErrorCodeExternalOpenFailed  = "EXTERNAL_OPEN_FAILED"
	ErrorCodeLocalReadFailed     = "LOCAL_READ_FAILED"
	ErrorCodeLocalWriteFailed    = "LOCAL_WRITE_FAILED"
	ErrorCodeSecretWriteFailed   = "SECRET_WRITE_FAILED"
	ErrorCodeSecretReadFailed    = "SECRET_READ_FAILED"
	ErrorCodeSecretNotConfigured = "SECRET_NOT_CONFIGURED"
	ErrorCodeAIUnauthorized      = "AI_UNAUTHORIZED"
	ErrorCodeAIRateLimited       = "AI_RATE_LIMITED"
	ErrorCodeAITimeout           = "AI_TIMEOUT"
	ErrorCodeAIResponseInvalid   = "AI_RESPONSE_INVALID"
	ErrorCodeAIConsentRequired   = "AI_CONSENT_REQUIRED"
	ErrorCodeAIRequestFailed         = "AI_REQUEST_FAILED"
	ErrorCodeDataRootTargetOccupied  = "DATA_ROOT_TARGET_OCCUPIED"
	ErrorCodeDataRootMigrateFailed   = "DATA_ROOT_MIGRATE_FAILED"
	ErrorCodeDataRootInvalid         = "DATA_ROOT_INVALID"
	ErrorCodeDataRootEmpty           = "DATA_ROOT_EMPTY"

	ErrorMessageInvalidArgument     = "Invalid local document request"
	ErrorMessageDocumentInvalid     = "Library document is invalid"
	ErrorMessageSettingsInvalid     = "Settings document is invalid"
	ErrorMessageImportInvalid       = "Import file is invalid"
	ErrorMessageExportInvalid       = "Export document is invalid"
	ErrorMessageURLInvalid          = "URL must use HTTP or HTTPS"
	ErrorMessageMetadataFetchFailed = "Failed to fetch page metadata"
	ErrorMessageExternalOpenFailed  = "Failed to open URL in system browser"
	ErrorMessageLocalReadFailed     = "Failed to read local document"
	ErrorMessageLocalWriteFailed    = "Failed to write local document"
	ErrorMessageCloudDraftDirty     = "Cloud draft is dirty"
	ErrorMessageSecretWriteFailed   = "Failed to write secret"
	ErrorMessageSecretReadFailed    = "Failed to read secret"
	ErrorMessageSecretNotConfigured = "AI API Key is not configured"
	ErrorMessageSecretEmpty         = "Secret value must not be empty"
	ErrorMessageAIUnauthorized      = "AI service rejected the API key"
	ErrorMessageAIRateLimited       = "AI service rate limit exceeded"
	ErrorMessageAITimeout           = "AI request timed out"
	ErrorMessageAIResponseInvalid   = "AI response could not be normalized"
	ErrorMessageAIConsentRequired   = "AI data consent is required for this API Base"
	ErrorMessageAIRequestFailed     = "AI request failed"
	ErrorMessageAIInvalidArgument   = "AI request arguments are invalid"
	ErrorMessageDataRootTargetOccupied = "Target directory already contains Linkit data"
	ErrorMessageDataRootMigrateFailed  = "Failed to migrate local data directory"
	ErrorMessageDataRootInvalid        = "Target data directory is invalid"
	ErrorMessageDataRootEmpty          = "No library or settings data available to migrate"

	// SecretServiceName 与 OS Keychain / Credential Manager 服务名对齐。
	SecretServiceName = "Linkit"
	// AIAPIKeySecretKey 是 AI Key 的逻辑键；前端仅可见 configured 状态。
	AIAPIKeySecretKey = "linkit.ai.api-key"
)
